title: Reducing Uncertainty
email: luiscostigan7@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Tokyo-based. Interests in effective altuism, data science, drums.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://valencia21.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: luiscostigan1
github_username:  valencia21

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
